# Generated by Django 4.0.4 on 2022-12-17 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('due_date', models.DateField(null=True)),
                ('scheldule_date', models.DateField(default=datetime.datetime(2022, 12, 24, 14, 39, 23, 596525))),
            ],
        ),
    ]
