# Generated by Django 4.0.4 on 2022-12-23 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='scheldule_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 30, 17, 16, 44, 279124)),
        ),
        migrations.AddField(
            model_name='task',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='voir.user'),
        ),
    ]
