# Generated by Django 4.0.4 on 2022-12-23 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voir', '0002_user_alter_task_scheldule_date_task_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='scheldule_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 30, 17, 57, 7, 890067)),
        ),
    ]
