# Generated by Django 4.0.4 on 2022-12-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
